modLoader="javafml"
loaderVersion="[37,)"
license="Open Source"

[[mods]]
modId="end_survival"
version="1.8"
displayName="End Survival"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="thesupermodder, MCreator(00001H)"
description='''
Survive in the end,get overworld passes,and more!
'''

[[dependencies.end_survival]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.end_survival]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.1]"
    ordering="NONE"
    side="BOTH"



